GET http://localhost:3010/beers

###
GET http://localhost:3010/beers/65995e8a6b9be41cfc8dc110

###
POST http://localhost:3010/beers
Content-Type: application/json

{
  "brand": "Kitzmann",
  "name": "Bergkirchweihbier",
  "strength": 5.5
}

###
PUT http://localhost:3010/beers/65995e8a6b9be41cfc8dc110
Content-Type: application/json

{
  "brand": "Kitzmann",
  "name": "Bergkirchweih Bier",
  "strength": 5.5
}

###
DELETE http://localhost:3010/beers/659ae85b5df5fcb4a0000000