GET http://localhost:3010/beers

###
GET http://localhost:3010/beers/6560a9ba5df5fcf284000001

###
POST http://localhost:3010/beers
Content-Type: application/json

{
  "brand": "Plörre",
  "name": "Würg",
  "strength": 4.3
}

###
PUT http://localhost:3010/beers/6560a9ba5df5fcf284000001
Content-Type: application/json

{
  "brand": "Kitzmann",
  "name": "Bergkirchweih Bier",
  "strength": 5.5
}

###
DELETE http://localhost:3010/beers/6560a9a95df5fcf284000000